---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis
  namespace: staging
spec:
  selector:
    matchLabels:
      app: redis
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: redis
      annotations:
        checksum/deployment: TMP_DEP_CHECKSUM
    spec:
      containers:
      - name: redis
        image: redis:5.0.3-alpine3.8
        imagePullPolicy: Always 
        resources:
          limits:
            cpu: 100m
            memory: 64M
          requests:
            cpu: 50m
            memory: 16M

---
kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: staging
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: redis